start ironclad 10 2U6RHU76AL6P8
choose 0
choose take 21 damage gain 250 gold
choose 0
choose x=2
play 1 0
play 2 0
play 3 0
end
play 3 1
play 1
play 3
end
play 2 1
play 3 1
choose 1
choose 0
choose 0
choose power through
proceed
choose x=2
play 3
play 1 0
play 2 0
end
play 1 0
play 4
play 1 0
end
play 3
play 3 0
play 1
end
play 5 0
play 2 0
end
play 5
play 1 0
play 2 0
choose 1
choose 0
choose 0
choose spot weakness
proceed
choose 0
choose take
choose hide
choose 0
choose 0
choose shop
choose membership card
choose purge
choose strike
confirm
choose shrug it off
leave
choose shop
choose true grit
leave
choose shop
leave
choose shop
leave
choose shop
choose searing blow
leave
choose shop
leave
choose shop
leave
choose shop
leave
choose shop
leave
choose shop
choose clothesline
choose fire breathing
leave
proceed
choose x=4
play 2 0
play 3
end
play 3
play 3
play 2 0
end
play 3 1
play 1 1
end
play 1 1
play 3 1
choose 0
choose 0
choose dark embrace
proceed
choose 0
choose smith
choose searing blow
confirm
proceed
choose x=4
choose gather gold
choose 0
choose x=4
play 3 0
play 1
play 2
end
play 1 0
play 1
play 1
end
potion use 0
play 2
play 3 0
end
play 1 0
play 1
play 2 0
end
play 3 0
choose 1
choose 0
choose 0
choose armaments
proceed
choose 0
choose open
choose 0
proceed
choose x=6
choose grow
choose armaments
confirm
choose 0
choose 0
potion use 1
play 2
play 2 1
play 1
end
play 4 1
play 3
play 2
end
play 4 0
play 3
end
play 3 0
play 4
end
play 3 1
play 1 1
choose 1
choose 0
choose 0
choose flame barrier
proceed
choose 0
play 1
play 2 0
end
play 3 3
play 1
end
play 1
potion use 1  2
play 3
choose 0
proceed
play 2
end
play 4
play 1 1
play 2 1
end
play 1
play 1
end
play 2
play 1
choose 1
proceed
play 1 1
end
play 1 2
choose 0
choose 0
choose metallicize
proceed
choose 0
choose rest
proceed
choose 0
play 4
play 3
end
play 3
play 4
play 1 0
end
play 3 0
play 3
play 2
end
play 5
play 5
play 1
end
play 3
play 3
end
play 1
play 1
play 1
end
play 5
play 1 0
end
play 3 0
play 3 0
end
play 2 0
play 3
end
play 4 1
choose 0
choose 0
choose offering
proceed
choose x=5
choose smith
choose searing blow+1
confirm
proceed
choose 0
play 2
play 1 0
end
play 2
play 2
end
play 4
play 1
play 2
end
play 3 0
play 4 0
end
play 4 0
play 3
play 1
end
play 1
play 2
end
play 4
play 6 0
play 7 0
play 5 0
end
play 1 0
play 1
play 2
end
play 5 0
play 4
end
play 5 0
play 4
play 4
potion use 0
end
play 1 0
play 4 0
play 3
end
play 2
play 2
end
play 1 0
play 3
play 1 0
end
play 2
play 3 0
end
choose 1
choose 0
choose 0
choose limit break
proceed
choose open
choose sozu
proceed
choose x=5
potion use 0
choose 0
play 6
play 2
play 5 1
play 1 1
end
play 1
play 3 1
play 2
end
play 3 0
play 1 0
end
play 4
play 2
play 2
play 5
play 2
choose 0
proceed
play 1 1
play 2 1
end
choose card
choose pommel strike+
choose stolen_gold
choose 0
proceed
choose 0
choose refuse
choose 0
choose 0
play 5 0
play 3 0
play 1 0
end
play 2
play 1
play 1 0
end
play 2
play 6
play 1
play 6
play 4 0
play 1
end
play 2 0
play 6 0
play 4 0
choose 1
choose 0
choose 0
choose sword boomerang+
proceed
choose 0
choose shop
choose apotheosis
choose red skull
choose purge
choose strike
confirm
choose brimstone
choose shockwave
choose dark embrace