start ironclad 10 3ESSK05Q3UNKS
choose 0
choose take 21 damage transform 2 cards
choose strike
choose strike
choose strike
choose bash
choose 0
choose x=1
autoplay
choose 0
choose 0
choose shrug it off
proceed
choose 0
autoplay
choose 1
choose 0
choose 0
choose warcry
proceed
choose x=3
autoplay
choose 0
choose 0
choose dropkick
proceed
choose 0
choose rummage
choose 0
choose x=3
autoplay
choose 0
choose 0
choose power through
proceed
choose 0
choose smith
choose shrug it off
confirm
proceed
choose x=4
autoplay
choose 1
choose 0
choose 0
choose dark embrace
proceed
choose 0
autoplay
choose 1
choose 0
choose 0
choose shrug it off
proceed
choose x=2
choose open
choose 0
choose 0
proceed
choose x=1
autoplay
choose 0
choose 0
choose 0
choose fiend fire
proceed
choose 0
choose shop
choose vajra
choose purge
choose pain
confirm
leave
proceed
choose x=1
choose smith
choose fiend fire
confirm
proceed
choose 0
proceed
choose 0
autoplay
choose 0
choose 0
choose 0
choose seeing red
proceed
choose 0
choose smith
choose shrug it off
confirm
proceed
choose 0
autoplay
choose 0
choose 0
choose corruption
proceed
choose open
choose runic pyramid
proceed
choose x=4
autoplay
choose 0
choose 0
skip
proceed
choose 0
choose shop
choose hand drill
leave
proceed
choose 0
choose elegance
choose shrug it off+
choose 0
choose 0
autoplay
choose 1
choose 0
choose 0
choose shockwave
proceed
choose x=4
choose accept
choose 0
choose x=4
choose smith
choose corruption
confirm
proceed
choose 0
autoplay
choose 0
choose 0
choose card
choose shockwave
choose emerald_key
proceed
choose 0
autoplay
choose 1
choose 0
choose 0
choose dark embrace
proceed
choose 0
choose open
choose 0
choose dropkick
proceed
choose x=1
choose desecrate
choose 0
choose 0
autoplay
choose 0
choose 0
choose shockwave
proceed
choose 0
autoplay
choose 0
choose 0
choose rampage
proceed
choose x=1
choose smith
choose shockwave
confirm
proceed
choose 0
autoplay
choose 1
choose 0
choose 0
choose cleave
proceed
choose 0
choose rest
proceed
choose 0
autoplay
choose 1
choose 0
choose 0
choose fiend fire
proceed
choose open
choose mark of pain
proceed
choose x=3
autoplay
choose 1
choose 0
choose 0
choose thunderclap+
proceed
choose x=4
autoplay
choose 0
choose 0
choose cleave+
proceed
choose 0
autoplay
choose 1
choose 0
choose 0
choose inflame+
proceed
choose x=5
choose shop
choose pen nib
choose purge
choose strike
confirm
choose flame barrier
choose essence of steel
choose immolate
choose true grit
leave
proceed
choose 0
autoplay
choose 1
choose 0
choose 0
choose disarm+
proceed
choose x=5
autoplay
choose 0
choose 0
choose 0
choose double tap
proceed
choose x=4
choose smith
choose immolate
confirm
proceed
choose 0
autoplay
choose 0
choose 0
choose feel no pain
proceed
choose x=4
choose open
choose 0
proceed
choose 0
autoplay
choose 1
choose 0
choose 0
choose armaments+
proceed
choose 0
proceed
choose 0
autoplay
choose 2
choose 0
choose 0
choose 0
choose thunderclap
proceed
choose 0
autoplay
choose 0
choose 0
skip
proceed
choose x=4
choose 0
choose 0
choose 0
proceed
choose 0
choose smith
choose fiend fire
confirm
proceed
choose 0
autoplay
proceed
choose 0
choose 0
choose 0
choose 0
proceed