start ironclad 10 2YZBUP6INUF2Q
choose 0
choose upgrade a card
choose bash
confirm
choose 0
choose x=3
play 3 0
play 3 0
play 3 0
end
play 3 0
play 2
end
play 1 0
play 2 0
play 2 0
choose 0
choose 0
choose true grit
proceed
choose 0
play 3 0
play 3 0
play 1
end
play 2 1
play 1
play 1
end
play 1 1
play 1 1
end
play 2 1
play 4 1
choose 0
choose 0
choose iron wave
proceed
choose x=5
play 3
play 1 0
play 2
end
play 2
play 1 0
play 1 0
end
play 3 0
play 2 0
play 2
end
play 1
play 1 0
play 1 0
end
play 3
play 3
play 2
end
play 1 0
play 1
play 3
end
play 4
play 1 0
play 1 0
end
play 2 0
play 2 0
choose 1
choose 0
choose 0
choose shrug it off
proceed
choose x=4
play 2
play 1 0
play 1
potion use 0
choose 0
play 2 0
end
play 1 0
play 1
play 2
end
play 2
play 2 0
play 1
end
play 2 0
play 1
play 2
end
play 4 0
play 1 0
end
play 2
play 2
play 3 0
end
play 4
play 3
play 1 1
end
play 4
play 4 0
play 3
end
play 1
play 2
play 2
end
play 1
play 4 0
end
play 1 0
play 1 0
play 3
end
play 3 0
play 2
end
play 1
play 1
play 2 0
end
play 3
play 1
play 1
end
play 1 1
play 3 1
end
play 1
play 1 1
play 3
end
play 2 1
choose 1
choose 0
choose 0
choose shockwave
proceed
choose x=4
play 1 0
play 3
potion use 0
choose 0
play 3
end
play 5 0
play 2 0
play 1
end
play 4
play 1 1
play 1
end
play 4
play 2 1
play 1 1
play 1 1
end
play 3 1
choose 1
choose 0
choose 0
choose spot weakness
proceed
choose x=4
choose smith
choose shrug it off
confirm
proceed
choose 0
play 1
play 1 0
end
play 3 0
play 4
play 1
end
play 1 0
play 1 0
play 2 0
potion use 0
end
play 2
play 4 0
play 3
end
play 1 0
play 4
play 1
end
play 5 0
play 1
end
play 2 0
play 2 0
play 2
end
play 1 0
play 1 0
play 2
end
play 3 0
play 4
play 4 0
end
play 1 0
play 1 0
choose 0
choose 0
choose 0
choose feed
proceed
choose 0
play 7
play 7 0
play 3 0
end
play 2
play 4 0
play 3 0
end
play 3
play 1 0
play 1
end
play 3
play 3 0
choose card
choose carnage
choose stolen_gold
choose 0
proceed
choose 0
choose open
choose 0
choose 0
proceed
choose 0
choose smith
choose feed
confirm
proceed
choose x=2
choose gather gold
choose 0
choose 0
play 5 0
play 4 1
end
play 1 2
play 2 2
play 3 2
end
play 5 3
play 2
end
play 3
play 1
end
play 5 3
choose 1
choose 0
choose 0
choose battle trance
proceed
choose x=3
choose rest
proceed
choose 0
choose forget
choose strike
confirm
choose 0
choose 0
choose smith
choose carnage
confirm
proceed
choose 0
play 6 0
play 2 0
end
play 4
play 2
play 2
end
play 3 0
play 1
play 1
end
play 5
play 5
play 5
play 3
end
play 4 0
play 2 0
end
play 3 0
play 2 0
play 2 0
end
play 3 0
play 2
play 3 0
end
play 1
play 3
play 1
play 4 0
end
play 1
play 3
play 1 0
end
play 1 0
play 3
play 5
play 1 0
end
play 5 0
play 3
play 1 0
play 5 0
end
play 1 0
play 4
play 2 0
end
play 3
play 7 0
play 1 0
play 1 0
choose 0
choose 0
choose reaper
proceed
choose open
choose fusion hammer
proceed
choose x=0
play 3 0
play 1 0
play 1
end
play 2
play 6 0
play 1 0
play 3
end
play 3 2
play 1
play 2
play 2
end
play 2
play 2
play 6 1
play 5
end
play 4
play 3
play 2 1
end
play 2 2
play 3 2
play 2
end
play 2
play 6 2
play 3 2
choose 1
choose 0
choose 0
choose cleave
proceed
choose x=1
choose refuse
choose 0
choose 0
choose shop
choose armaments
choose oddly smooth stone
choose purge
choose strike
confirm
choose meal ticket
choose ghostly armor
leave
proceed
choose x=0
play 6 0
play 2 0
play 1
potion use 1
end
play 1
choose 0
proceed
play 2
play 2
play 1
end
play 2
play 1 0
play 2
end
play 1
play 1 0
play 2
play 1
end
play 5 0
play 3
play 1
play 1 0
end
play 2 0
play 1
choose 0
proceed
play 1 0
play 2
end
play 1
play 7 0
play 1 0
play 3 0
choose 0
choose 0
choose anger
proceed
choose 0
play 2 1
play 2
play 2
choose 0
proceed
play 6 0
play 4 0
end
play 3 0
play 2
play 1
end
play 2
play 2 1
end
play 4
play 4
choose 3
proceed
play 6 1
play 4 1
end