start ironclad 10 S9NZU7BQMS9W
choose 0
choose lose 8 max hp choose a rare card to obtain
choose fiend fire
choose 0
choose x=0
play 2 1
play 2 1
play 2 1
end
play 5 0
choose 1
choose 0
choose 0
choose armaments
proceed
choose x=1
choose pray
choose armaments
confirm
choose 0
choose x=1
play 4 0
play 2 0
end
play 4
play 4 0
choose 0
choose 0
choose shrug it off
proceed
choose x=1
choose 0
choose 0
choose card0
choose card5
choose blind
choose fire breathing
choose blind
choose card1
choose demon form
choose blind
choose demon form
choose blind
choose 0
choose x=1
play 3
play 3
play 2 0
end
play 1
play 5 0
end
play 1
play 1 0
play 1
end
play 2
play 3
play 3
end
play 3 0
play 3
play 2
end
play 4 0
choose 0
choose 0
choose pommel strike
proceed
choose 0
choose smith
choose fiend fire
confirm
proceed
choose 0
play 5 0
play 2
end
play 1
play 3
play 3 0
end
play 5 0
play 4 1
choose 0
choose 0
choose cleave
proceed
choose x=2
play 5
play 1
play 2
end
play 2 0
play 4
end
play 1 0
play 1
play 1
end
play 4
play 1
play 2 0
end
play 2 0
play 5 0
choose 0
choose 0
choose sword boomerang
proceed
choose x=2
choose open
choose 0
proceed
choose 0
choose shop
choose true grit
choose purge
choose strike
confirm
choose dark embrace
leave
proceed
choose 0
choose gather gold
choose 0
choose x=2
choose smith
choose shrug it off
confirm
proceed
choose x=2
choose reach inside
choose deeper
choose deeper
choose deeper
choose deeper
choose 0
choose 0
play 5
play 2 0
play 1
end
play 3 0
choose 0
choose 0
choose headbutt
proceed
choose 0
choose smith
choose pommel strike
confirm
proceed
choose 0
play 1 0
play 1 0
end
play 4
play 3
play 2
end
play 4
play 2 0
choose 0
play 1
end
play 3
play 4
play 2
end
play 2 0
play 5 0
end
play 3
play 4
play 1
end
play 3
play 3
play 3
end
play 1
play 2
play 4
end
play 5 0
play 4
play 3 0
end
potion use 0
play 3
play 4
play 3
end
play 5 0
play 1
play 5 0
end
play 4 0
play 1
play 5 0
end
play 2
play 4
play 1 0
end
play 3
play 2
play 2
end
play 1
play 1
play 2
end
play 3 0
play 4
play 4 0
end
play 5
play 3
play 3
end
play 2 0
play 2
play 1
end
play 4
play 3
play 2
end
play 3 0
play 1
play 2 0
end
play 3
play 1 0
play 1
end
play 3
play 2 0
play 1
end
play 3
play 2 0
choose 1
choose 0
choose 0
choose corruption
proceed
choose open
choose mark of pain
proceed
choose x=5
play 2
play 4
play 2
play 4
play 3
play 1
play 4 0
play 1
end
play 2 0
play 4
play 6 2
choose 4
play 5
play 5
end
play 2 2
play 3
play 2 1
end
play 2 1
choose 0
choose 0
choose iron wave+
proceed
choose 0
choose shop
choose shockwave
choose inflame
leave
proceed
choose x=4
choose refuse
choose 0
choose x=3
choose desecrate
choose 0
choose x=4
play 1
play 3 0
play 2
play 3
end
play 4 0
choose 0
play 3
play 3
play 1 0
potion use 0  0
end
play 5
play 1 0
play 2
end
play 2
play 6
play 2 0
play 2
play 4 0
choose 0
choose 0
choose seeing red
proceed
choose 0
play 5
play 3
play 1
play 1
end
play 2 0
play 3 0
choose 5
play 2
play 3 0
end
play 2 0
play 3 0
play 4
play 4
end
play 2
play 3
end
play 5
play 2
end
play 5
play 3 1
play 1
end
play 1
choose 0
choose 0
choose 0
choose flex
proceed
choose 0
choose rest
proceed
choose 0
choose leave
choose 0
choose 0
choose open
choose 0
choose 0
proceed
choose 0
choose offer gold
choose 0
choose x=2
play 1
play 2
play 3
play 2
play 1 0
end
play 2
play 2
play 3
play 1
play 1 0
end
play 5
play 2 0
play 2 0
end
play 1 0
play 2 0
play 4
play 3
play 1
play 2 0
play 2 0
choose 8
end
play 4
play 2
play 4
play 3
play 4 0
play 3 0
choose 2
choose 0
choose 0
choose 0
choose infernal blade
proceed
choose x=2
choose shop
choose impervious
choose paper phrog
leave
proceed
choose 0
play 5
play 1
play 4 0
play 2 0
play 1
play 1
potion use 0
end
proceed